---

- hosts: localhost
  connection: local
  tasks:

    - name: Create host dml.common
      centreon_host:
        state: present
        name: dml.common
        poller: Central
        host_ip: 10.69.XX.XXX
        username: admin
        hostgroups:
          - All
          - All-Servers
          - All-Servers-Linux
          - All-Servers-Linux-Debian
        host_templates:
          - Generic
          - Generic-Linux
          - Generic-Linux-Debian
        password: "{{ vault_centreon_admin_password }}"
        reload_conf: no

    - name: Create service diskfree for host dml.common
      centreon_service:
        state: present
        host: dml.common
        name: Disk-Free-/srv/dml
        poller: Central
        service_template: NRPE-Linux-DiskFree-Mountpoint
        macros:
          - CRITICAL;15%
          - WARNING;20%
          - DISK;/srv/dml
        username: admin
        password: "{{ vault_centreon_admin_password }}"
        reload_conf: no

    - name: Create service export for host dml.common
      centreon_service:
        state: present
        host: dml.common
        name: Export-/srv/dml
        poller: Central
        service_template: NRPE-NFS-Exports
        macros:
          - NFSHOST;localhost
          - PATH;/srv/dml
        username: admin
        password: "{{ vault_centreon_admin_password }}"
        reload_conf: yes