---

- hosts: localhost
  connection: local
  tasks:

    - name: Create host dml.common
      centreon_host:
        state: present
        name: dml.common
        poller: Central
        host_ip: 10.69.XX.XXX
        username: admin
        hostgroups:
          - All
          - All-Servers
          - All-Servers-Linux
          - All-Servers-Linux-Debian
        host_templates:
          - Generic
          - Generic-Linux
          - Generic-Linux-Debian
        password: {{ centreon_admin_password }}
        reload_conf: yes

    - name: Create service Memory for host dml.common
      centreon_service:
        state: present
        host: sdml.common
        name: Memory
        poller: Central
        service_template: NRPE-Linux-Memory
        macros:
          - CRITICAL;80
          - WARNING;70
        username: admin
        password: "{{ admin_centreon_pass }}"
        reload_conf: no